# Generated by Django 4.1.1 on 2022-10-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_upper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_upper',
        ),
    ]
