# Generated by Django 4.1.1 on 2022-09-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_date_created_alter_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_created',)},
        ),
    ]
