# Generated by Django 4.1.1 on 2022-09-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_item_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='number',
            new_name='qty',
        ),
    ]
