# Generated by Django 4.1.1 on 2022-09-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='product',
        ),
    ]
