# Generated by Django 4.1.1 on 2022-09-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_name_item_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_items',
            field=models.ManyToManyField(auto_created=True, to='api.item'),
        ),
    ]
