# Generated by Django 4.1.1 on 2022-09-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_item_user_alter_cart_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
