# Generated by Django 4.1.1 on 2022-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_cart_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_items',
            field=models.ManyToManyField(blank=True, null=True, to='api.item'),
        ),
    ]
