# Generated by Django 4.1.1 on 2022-10-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_after_discount',
            field=models.FloatField(default=0),
        ),
    ]
